joinfaces:
  jsf:
    facelets-skip-comments: true
  omnifaces:
    faces-views-scan-paths: /*.xhtml

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-root.xml

noble:
  vendor:
    copyright: Copyright © 2022 norcane
